### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by ChrisBeeley** [Public-Health-Scotland/learnr-online#4]
This repo is amazing! I can't believe I've never seen it before!

Are the materials available under an open source licence? Still amazing if not, but I thought I'd ask the question.

Thanks :relaxed:

**Comment by rmccreath** [comment]
Hey @ChrisBeeley - absolutely, I've just added the MIT license so very much available under open source! I'll continue expanding this along with the Knowledge Base and will always be open to feedback, thanks 😄

**Comment by ChrisBeeley** [comment]
Thanks! You rock! 😎
